random_forest:
  n_estimators: 100
  max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 1
  random_state: 42
  # 분류를 위한 추가 파라미터
  class_weight: 'balanced'  # 클래스 불균형 처리
  criterion: 'gini'        # 분류 기준